### ISSUE TITLE
Error starting the sample

### ISSUE THREAD

**Issue by jogule** [PartnerCenterSamples/partnercenter-restapi-nodejs#1]
When I try to start the sample it connect but it seems that when it gets the list of customers the app raises an exception:

$ npm run start

> partnercenter-restapi-nodejs@1.0.0 start C:\Users\JONGUZ\partnercenter-restapi-nodejs
> npm run build && node ./src/index.js

> partnercenter-restapi-nodejs@1.0.0 prebuild C:\Users\JONGUZ\partnercenter-restapi-nodejs
> rm -rf typings && typings install

+-- chalk
`-- debug
  `-- ms

> partnercenter-restapi-nodejs@1.0.0 build C:\Users\JONGUZ\partnercenter-restapi-nodejs
> tsc

.. Authenticating the user as App Only
Logging into Azure AD..
.. obtained AAD access token.
Obtaining Partner Center token..
.. obtained Partner Center access token.
Checking if the domain 'wingtiptoys' is available...
.. domain is NOT available.
Getting list of customers...
undefined:1
琢瑯污潃湵≴㔺∬瑩浥≳嬺≻摩㨢愢ㄵ㘸㉤ⵥ㠳㉤㐭戸ⴵ挹摥㠭㌰㤶扥㤰晤∹∬潣灭湡偹潲楦敬㨢≻整慮瑮摉㨢愢ㄵ㘸㉤ⵥ㠳㉤㐭戸ⴵ挹摥㠭㌰㤶扥㤰晤∹∬潤慭湩㨢䄢慄畴偭牡湴牥敃瑮牥偁⹉湯業牣獯景⹴潣≭∬潣灭湡乹浡≥∺⹁䐠瑡浵䌠牯潰慲楴湯Ⱒ氢湩獫㨢≻敳晬㨢≻牵≩∺振獵潴敭獲愯ㄵ㘸㉤ⵥ㠳㉤㐭戸ⴵ挹摥㠭㌰㤶扥㤰晤⼹牰景汩獥振浯慰祮Ⱒ洢瑥潨≤∺䕇≔∬敨摡牥≳嬺絝ⱽ愢瑴楲畢整≳笺漢橢捥呴灹≥∺畃瑳浯牥潃灭湡偹潲楦敬索ⱽ爢汥瑡潩獮楨呰偯牡湴牥㨢爢獥汥敬≲∬楬歮≳笺猢汥≦笺產楲㨢⼢畣瑳浯牥⽳㕡㠱搶攲㌭搸ⴲ㠴㕢㤭散ⵤ〸㘳改ぢ搹㥦Ⱒ洢瑥潨≤∺䕇≔∬敨摡牥≳嬺絝ⱽ愢瑴楲畢整≳笺漢橢捥呴灹≥∺畃瑳浯牥索ⱽ≻摩㨢㘢慡㙣㥣ⴹ敡〵㐭㘱ⴳ挹㕥㘭㔸㌰㌱搵㝦∶∬潣灭湡偹潲楦敬㨢≻整慮瑮摉㨢㘢慡㙣㥣ⴹ敡〵㐭㘱ⴳ挹�

SyntaxError: Unexpected token 琢 in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\JONGUZ\partnercenter-restapi-nodejs\src\pcCustomers.js:55:33)
    at Request.self.callback (C:\Users\JONGUZ\partnercenter-restapi-nodejs\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\JONGUZ\partnercenter-restapi-nodejs\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\JONGUZ\partnercenter-restapi-nodejs\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! partnercenter-restapi-nodejs@1.0.0 start: `npm run build && node ./src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the partnercenter-restapi-nodejs@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JONGUZ\AppData\Roaming\npm-cache\_logs\2018-03-28T19_45_38_421Z-debug.log

**Comment by indianazhao** [comment]
Try to add content-type in the request header
```node
let requestHeaders: request.Headers = <request.Headers>{
  'Authorization': 'Bearer ' + this.partnerCenterToken,
  'MS-Contract-Version': 'v1',
  'MS-CorrelationId': uuid.v4(),
  'MS-RequestId': uuid.v4(),
  'X-Locale': 'en-US',
  'Content-type': 'text/json; charset=utf-8'  // <-- this line
};
````

And parse the body directly without the string process.
```node
/* // strip off BOM characters "FF FE" for UTF-16LE
let stripped: string = body.substring(2, body.length);
// convert string from UTF-16LE => UTF-8
let converted: Buffer = encoding.convert(stripped, 'UTF-8', 'UTF-16LE');
// take UTF-8 string & parse as JSON
let json: any = JSON.parse(converted.toString());
deferred.resolve(json.items); */

// replace the above codes with the below ones
const jbody = JSON.parse(body);
deferred.resolve(jbody['items']);
```
